name: riki_and_morti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  graphql_flutter: ^5.2.1
  get_it: ^9.2.0
  equatable: ^2.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  talker_flutter: ^5.1.13
  talker_bloc_logger: ^5.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
